version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  cooldown:
    default-days: 5
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 5
